# Generated by Django 5.2.7 on 2025-11-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_campsite_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='campsite',
            name='image_url',
            field=models.URLField(blank=True, help_text='Primary image hosted on ImageKit', max_length=500, null=True),
        ),
    ]
