# Generated by Django 5.2.7 on 2025-11-06 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_campsite_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campsite',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this campsite has been approved for display'),
        ),
        migrations.AddField(
            model_name='campsite',
            name='suggested_by',
            field=models.ForeignKey(blank=True, help_text='User who originally suggested this campsite', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_campsites', to=settings.AUTH_USER_MODEL),
        ),
    ]
