# Generated by Django 5.2.7 on 2025-11-06 15:58

from django.db import migrations


def approve_existing_campsites(apps, schema_editor):
    """Mark all existing campsites as approved."""
    Campsite = apps.get_model("core", "Campsite")
    Campsite.objects.filter(is_approved=False).update(is_approved=True)


def reverse_approval(apps, schema_editor):
    """Reverse operation - no-op as we don't want to unapprove existing campsites."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_campsite_is_approved_campsite_suggested_by'),
    ]

    operations = [
        migrations.RunPython(approve_existing_campsites, reverse_approval),
    ]
