# Generated by Django 5.2.7 on 2025-11-06 16:30

from django.db import migrations


def convert_country_names_to_codes(apps, schema_editor):
    """Convert existing country names to 2-letter codes."""
    Campsite = apps.get_model("core", "Campsite")
    
    # Mapping of country names to codes
    country_mapping = {
        'Albania': 'AL',
        'Andorra': 'AD',
        'Austria': 'AT',
        'Belarus': 'BY',
        'Belgium': 'BE',
        'Bosnia and Herzegovina': 'BA',
        'Bulgaria': 'BG',
        'Croatia': 'HR',
        'Cyprus': 'CY',
        'Czech Republic': 'CZ',
        'Denmark': 'DK',
        'Estonia': 'EE',
        'Finland': 'FI',
        'France': 'FR',
        'Germany': 'DE',
        'Greece': 'GR',
        'Hungary': 'HU',
        'Iceland': 'IS',
        'Ireland': 'IE',
        'Italy': 'IT',
        'Kosovo': 'XK',
        'Latvia': 'LV',
        'Liechtenstein': 'LI',
        'Lithuania': 'LT',
        'Luxembourg': 'LU',
        'Malta': 'MT',
        'Moldova': 'MD',
        'Monaco': 'MC',
        'Montenegro': 'ME',
        'Netherlands': 'NL',
        'North Macedonia': 'MK',
        'Norway': 'NO',
        'Poland': 'PL',
        'Portugal': 'PT',
        'Romania': 'RO',
        'Russia': 'RU',
        'San Marino': 'SM',
        'Serbia': 'RS',
        'Slovakia': 'SK',
        'Slovenia': 'SI',
        'Spain': 'ES',
        'Sweden': 'SE',
        'Switzerland': 'CH',
        'Ukraine': 'UA',
        'United Kingdom': 'GB',
        'Vatican City': 'VA',
    }
    
    for campsite in Campsite.objects.all():
        # Try to match the country name
        if campsite.country in country_mapping:
            campsite.country = country_mapping[campsite.country]
            campsite.save(update_fields=['country'])
        else:
            # If no match found, try case-insensitive match
            for name, code in country_mapping.items():
                if campsite.country.lower() == name.lower():
                    campsite.country = code
                    campsite.save(update_fields=['country'])
                    break


def reverse_conversion(apps, schema_editor):
    """Reverse operation - convert codes back to names."""
    Campsite = apps.get_model("core", "Campsite")
    
    # Reverse mapping
    code_to_name = {
        'AL': 'Albania',
        'AD': 'Andorra',
        'AT': 'Austria',
        'BY': 'Belarus',
        'BE': 'Belgium',
        'BA': 'Bosnia and Herzegovina',
        'BG': 'Bulgaria',
        'HR': 'Croatia',
        'CY': 'Cyprus',
        'CZ': 'Czech Republic',
        'DK': 'Denmark',
        'EE': 'Estonia',
        'FI': 'Finland',
        'FR': 'France',
        'DE': 'Germany',
        'GR': 'Greece',
        'HU': 'Hungary',
        'IS': 'Iceland',
        'IE': 'Ireland',
        'IT': 'Italy',
        'XK': 'Kosovo',
        'LV': 'Latvia',
        'LI': 'Liechtenstein',
        'LT': 'Lithuania',
        'LU': 'Luxembourg',
        'MT': 'Malta',
        'MD': 'Moldova',
        'MC': 'Monaco',
        'ME': 'Montenegro',
        'NL': 'Netherlands',
        'MK': 'North Macedonia',
        'NO': 'Norway',
        'PL': 'Poland',
        'PT': 'Portugal',
        'RO': 'Romania',
        'RU': 'Russia',
        'SM': 'San Marino',
        'RS': 'Serbia',
        'SK': 'Slovakia',
        'SI': 'Slovenia',
        'ES': 'Spain',
        'SE': 'Sweden',
        'CH': 'Switzerland',
        'UA': 'Ukraine',
        'GB': 'United Kingdom',
        'VA': 'Vatican City',
    }
    
    for campsite in Campsite.objects.all():
        if campsite.country in code_to_name:
            campsite.country = code_to_name[campsite.country]
            campsite.save(update_fields=['country'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_approve_existing_campsites'),
    ]

    operations = [
        migrations.RunPython(convert_country_names_to_codes, reverse_conversion),
    ]
