# Generated by Django 5.2.7 on 2025-11-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_campsite_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='campsite',
            name='is_premium',
            field=models.BooleanField(db_index=True, default=False, help_text='Premium campsites are featured at the top of listings'),
        ),
    ]
