# Generated by Django 5.2.7 on 2025-11-06 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_campsite_is_premium'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampsiteLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.campsite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campsite_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campsite Like',
                'verbose_name_plural': 'Campsite Likes',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'campsite'), name='unique_campsite_like')],
            },
        ),
    ]
