# Generated by Django 5.2.7 on 2025-11-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_campsitelike'),
    ]

    operations = [
        migrations.AddField(
            model_name='campsite',
            name='town',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
