# Generated by Django 5.2.7 on 2025-11-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='campsite',
            name='province',
            field=models.CharField(blank=True, help_text='Province, state, or region', max_length=200),
        ),
        migrations.AddField(
            model_name='campsite',
            name='type',
            field=models.CharField(blank=True, choices=[('BEACH', 'Beach'), ('MOUNTAIN', 'Mountain'), ('FOREST', 'Forest'), ('CITY', 'City'), ('SPORTS', 'Sports')], help_text='Type of campsite', max_length=20),
        ),
    ]
